"""Response models for the analysis API."""

from datetime import datetime
from pydantic import BaseModel, Field


class StopLoss(BaseModel):
    """Stop-loss recommendation with reasoning."""
    price: float
    reason: str


class TakeProfitTarget(BaseModel):
    """Individual take-profit target."""
    label: str = Field(..., description="e.g. 'TP1', 'TP2', 'TP3'")
    price: float
    reason: str


class EntryZone(BaseModel):
    """Suggested entry price range."""
    low: float
    high: float


class TradingAnalysis(BaseModel):
    """Core trading advice generated by the LLM."""
    trading_thesis: str = Field(
        ..., description="Core reason for the trade recommendation"
    )
    confidence_level: str = Field(
        ..., description="Confidence: 'high', 'medium', or 'low'"
    )
    confidence_reason: str = Field(
        ..., description="Why this confidence level was assigned"
    )
    direction: str = Field(
        ..., description="Trade direction: 'long' or 'short'"
    )
    entry_zone: EntryZone
    stop_loss: StopLoss
    take_profit_targets: list[TakeProfitTarget] = Field(
        ..., min_length=2, description="At least 2-3 TP targets"
    )


class MACDData(BaseModel):
    """MACD indicator values."""
    value: float
    signal: float
    histogram: float


class BollingerData(BaseModel):
    """Bollinger Bands values."""
    upper: float
    middle: float
    lower: float


class IndicatorData(BaseModel):
    """Classical technical indicator values."""
    rsi_14: float | None = None
    macd: MACDData | None = None
    bollinger: BollingerData | None = None
    sma_20: float | None = None
    ema_50: float | None = None


class OrderBlock(BaseModel):
    """SMC Order Block."""
    type: str = Field(..., description="'bullish' or 'bearish'")
    zone: list[float] = Field(..., description="[low, high] price range")
    timeframe: str


class FairValueGap(BaseModel):
    """SMC Fair Value Gap."""
    type: str = Field(..., description="'bullish' or 'bearish'")
    zone: list[float] = Field(..., description="[low, high] price range")
    timeframe: str


class SMCData(BaseModel):
    """Smart Money Concepts analysis data."""
    order_blocks: list[OrderBlock] = Field(default_factory=list)
    fair_value_gaps: list[FairValueGap] = Field(default_factory=list)
    structure: str | None = Field(
        None, description="e.g. 'BOS_bullish', 'CHoCH_bearish'"
    )
    liquidity_sweeps: list[str] = Field(default_factory=list)


class AnalysisDetails(BaseModel):
    """Raw analysis data behind the trading advice."""
    patterns_detected: list[str] = Field(default_factory=list)
    indicators: IndicatorData = Field(default_factory=IndicatorData)
    smc: SMCData = Field(default_factory=SMCData)
    timeframes_analyzed: list[str] = Field(default_factory=list)


class AnalysisResponse(BaseModel):
    """Full response from the /api/v1/analyze endpoint."""
    symbol: str
    market: str
    mode: str
    timestamp: datetime
    current_price: float = Field(..., description="The price at the time of analysis")
    analysis: TradingAnalysis | None = Field(
        None, description="LLM-generated trading advice. None if LLM failed."
    )
    details: AnalysisDetails
